package Lisek573.git;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import Lisek573.git.Account;

public class AccountDBManager {

	private Connection conn;
	
	private Statement stmt;
	
	private PreparedStatement addAccountStmt;
	private PreparedStatement getAccountsStmt;
	
	
	public AccountDBManager()
	{
		try {
			conn= DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/workdb");
					
			stmt=conn.createStatement();
			boolean AccountTableExists=false;
			
			ResultSet rs= conn.getMetaData().getTables(null, null, null, null);
			
			while(rs.next())
			{
				if("Account".equalsIgnoreCase(rs.getString("TABLE_NAME")))
					{
						AccountTableExists=true;
						break;
					}
			}
			
			
			if(!AccountTableExists)
			{
				stmt.executeUpdate("" +
					"CREATE TABLE Account(" +
					"id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
					"name varchar(20)," +
					"" +
					")");
			}
			
			addAccountStmt=conn.prepareStatement("" +
					"INSERT INTO Account (name) VALUES (?)" +
					"");
			
			getAccountsStmt=conn.prepareStatement("" +
					"SELECT * FROM Account" +
					"");
			
			
			
		} catch (SQLException e) {
			
			e.printStackTrace();
		}
	}
	
	public void addAccount(Account p)
	{
		try {
			addAccountStmt.setString(1, p.getSurname());
			
			addAccountStmt.executeUpdate();
			
		} catch (SQLException e) {
			
			e.printStackTrace();
		}
	
	}
	
	public List<Account> getAllAccounts()
	{
		List<Account> Accounts=new ArrayList<Account>();
		
		try {
			ResultSet rs= getAccountsStmt.executeQuery();
			
			while(rs.next())
			{
				Accounts.add(new Account(rs.getString("name"), rs.getString("name"), null));
			}
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return Accounts;
	}
	
	
}